/*
 * Configuration de démarrage pour la migration du schéma de base de données et l'initialisation H2.
 */



package com.farm.tinyfarm.config;

import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class SchemaMigrationConfig {

    @Bean
    @Order(0)
    CommandLineRunner migrateLegacyMarcheTable(JdbcTemplate jdbcTemplate) {
        return args -> {
            Integer marcheTableCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MARCHE'",
                Integer.class
            );

            if (marcheTableCount == null || marcheTableCount == 0) {
                return;
            }

            List<String> primaryKeyColumns = jdbcTemplate.query(
                """
                SELECT COLUMN_NAME
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE TABLE_NAME = 'MARCHE'
                  AND CONSTRAINT_NAME IN (
                      SELECT CONSTRAINT_NAME
                      FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                      WHERE TABLE_NAME = 'MARCHE'
                        AND CONSTRAINT_TYPE = 'PRIMARY KEY'
                  )
                ORDER BY ORDINAL_POSITION
                """,
                (rs, rowNum) -> rs.getString("COLUMN_NAME")
            );

            Integer legacyIdFermeColumnCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MARCHE' AND COLUMN_NAME = 'ID_FERME'",
                Integer.class
            );

            boolean wrongPrimaryKey = primaryKeyColumns.size() != 1 || !"ID_OFFRE".equals(primaryKeyColumns.get(0));
            boolean hasLegacyIdFermeColumn = legacyIdFermeColumnCount != null && legacyIdFermeColumnCount > 0;

            if (!wrongPrimaryKey && !hasLegacyIdFermeColumn) {
                return;
            }

            jdbcTemplate.execute("DROP TABLE IF EXISTS marche_migration");
            jdbcTemplate.execute("""
                CREATE TABLE marche_migration (
                    id_offre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    produit VARCHAR(255),
                    quantite INTEGER,
                    prix_unitaire INTEGER,
                    ferme_id_ferme INTEGER,
                    CONSTRAINT fk_marche_migration_ferme
                        FOREIGN KEY (ferme_id_ferme) REFERENCES ferme(id_ferme)
                )
                """);

            jdbcTemplate.execute("""
                INSERT INTO marche_migration (produit, quantite, prix_unitaire, ferme_id_ferme)
                SELECT produit, quantite, prix_unitaire, COALESCE(ferme_id_ferme, id_ferme)
                FROM marche
                WHERE COALESCE(ferme_id_ferme, id_ferme) IS NOT NULL
                """);

            jdbcTemplate.execute("DROP TABLE marche");
            jdbcTemplate.execute("ALTER TABLE marche_migration RENAME TO marche");
        };
    }

    @Bean
    @Order(1)
    CommandLineRunner dropLegacyAnimalUniqueFarmIndexes(JdbcTemplate jdbcTemplate) {
        return args -> {
            Integer animalTableCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ANIMAL'",
                Integer.class
            );

            if (animalTableCount == null || animalTableCount == 0) {
                return;
            }

            Integer legacyUniqueIndexCount = jdbcTemplate.queryForObject(
                """
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.INDEX_COLUMNS ic
                JOIN INFORMATION_SCHEMA.INDEXES i
                  ON i.TABLE_NAME = ic.TABLE_NAME
                 AND i.INDEX_NAME = ic.INDEX_NAME
                WHERE ic.TABLE_NAME = 'ANIMAL'
                  AND ic.COLUMN_NAME IN ('ID_FERME', 'IDFERME')
                  AND i.INDEX_TYPE_NAME = 'UNIQUE INDEX'
                """,
                Integer.class
            );

            if (legacyUniqueIndexCount == null || legacyUniqueIndexCount == 0) {
                return;
            }

            jdbcTemplate.execute("DROP TABLE IF EXISTS animal_migration");
            jdbcTemplate.execute("""
                CREATE TABLE animal_migration (
                    id_animal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    a_ete_traite BOOLEAN DEFAULT FALSE NOT NULL,
                    a_mange BOOLEAN DEFAULT FALSE NOT NULL,
                    age INTEGER DEFAULT 0 NOT NULL,
                    est_malade BOOLEAN DEFAULT FALSE NOT NULL,
                    jauge_faim INTEGER DEFAULT 100 NOT NULL,
                    jauge_hydratation INTEGER DEFAULT 100 NOT NULL,
                    jauge_proprete INTEGER DEFAULT 100 NOT NULL,
                    jauge_sante INTEGER DEFAULT 100 NOT NULL,
                    nom VARCHAR(255),
                    poids FLOAT DEFAULT 0 NOT NULL,
                    role TINYINT,
                    sexe TINYINT,
                    stade TINYINT,
                    type_animal TINYINT,
                    id_ferme INTEGER,
                    CONSTRAINT fk_animal_migration_ferme
                        FOREIGN KEY (id_ferme) REFERENCES ferme(id_ferme)
                )
                """);

            jdbcTemplate.execute("""
                INSERT INTO animal_migration (
                    id_animal,
                    a_ete_traite,
                    a_mange,
                    age,
                    est_malade,
                    jauge_faim,
                    jauge_hydratation,
                    jauge_proprete,
                    jauge_sante,
                    nom,
                    poids,
                    role,
                    sexe,
                    stade,
                    type_animal,
                    id_ferme
                )
                SELECT
                    id_animal,
                    a_ete_traite,
                    a_mange,
                    age,
                    est_malade,
                    jauge_faim,
                    jauge_hydratation,
                    jauge_proprete,
                    jauge_sante,
                    nom,
                    poids,
                    role,
                    sexe,
                    stade,
                    type_animal,
                    id_ferme
                FROM animal
                """);

            jdbcTemplate.execute("DROP TABLE animal");
            jdbcTemplate.execute("ALTER TABLE animal_migration RENAME TO animal");
        };
    }

    @Bean
    @Order(2)
    CommandLineRunner addAnimalFastingCounterColumn(JdbcTemplate jdbcTemplate) {
        return args -> {
            Integer animalTableCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ANIMAL'",
                Integer.class
            );

            if (animalTableCount == null || animalTableCount == 0) {
                return;
            }

            Integer fastingColumnCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ANIMAL' AND COLUMN_NAME = 'JOURS_JEUNE_CONSECUTIFS'",
                Integer.class
            );

            if (fastingColumnCount != null && fastingColumnCount > 0) {
                return;
            }

            jdbcTemplate.execute(
                "ALTER TABLE animal ADD COLUMN jours_jeune_consecutifs INTEGER DEFAULT 0 NOT NULL"
            );
        };
    }
}
