spring.application.name=tinyfarm

spring.datasource.url=jdbc:h2:file:./data/tinyfarm-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.oauth2.client.registration.github.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_ID:dummy-client-id}
spring.security.oauth2.client.registration.github.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_SECRET:dummy-client-secret}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.provider.github.user-name-attribute=login

tinyfarm.dev.cleanup-legacy-local-users=true
tinyfarm.dev.seed-local-users=false

server.forward-headers-strategy=framework
