spring.application.name=tinyfarm
spring.security.oauth2.client.registration.github.client-id=Ov23ct67ayf2KUIRxn9P
spring.security.oauth2.client.registration.github.client-secret=67462d89b3d9a9ba6733152bb1325cf3192326aa
spring.security.oauth2.client.provider.github.user-name-attribute=login