ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_oeuf INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_lait INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_lapin INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_eau INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_nourriture INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS ferme ADD COLUMN IF NOT EXISTS derniere_ponte_oeufs TIMESTAMP;
ALTER TABLE IF EXISTS animal DROP CONSTRAINT IF EXISTS UKPWE6MWBGYK7D88TRDCSFD3XRU;
