# Script SQL d'initialisation et schéma pour la base de données embarquée H2 de TinyFarm.

ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_oeuf INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_lait INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_lapin INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_eau INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS remise ADD COLUMN IF NOT EXISTS stock_nourriture INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS ferme ADD COLUMN IF NOT EXISTS jour_actuel INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE IF EXISTS ferme ADD COLUMN IF NOT EXISTS achats_collectivite_restants INTEGER DEFAULT 12 NOT NULL;
ALTER TABLE IF EXISTS animal ADD COLUMN IF NOT EXISTS jours_malade_consecutifs INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE IF EXISTS animal ADD COLUMN IF NOT EXISTS a_bu BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE IF EXISTS animal DROP CONSTRAINT IF EXISTS UKPWE6MWBGYK7D88TRDCSFD3XRU;
UPDATE ferme SET jour_actuel = 1 WHERE jour_actuel IS NULL;
UPDATE ferme SET achats_collectivite_restants = 12 WHERE achats_collectivite_restants IS NULL;
UPDATE animal SET jours_malade_consecutifs = 0 WHERE jours_malade_consecutifs IS NULL;
UPDATE animal SET a_bu = FALSE WHERE a_bu IS NULL;
